import platform

import mne
import mne_bids
import mne_connectivity
import mne_faster
import mne_nirs
import mne_realtime
import mne_features
import mne_rsa
import mne_microstates
import mne_ari
import mne_kit_gui
if platform.system() != 'Windows':
    import mne_icalabel
import autoreject
import pyprep
import darkdetect
import qdarkstyle
import openpyxl
import xlrd
import pingouin
import pycircstat
import pactools
import tensorpac
import emd
import neurodsp
import bycycle
import fooof
import coloredlogs
import json_tricks
import fire
import dask
import distributed
import openneuro
import sleepecg
import neurokit2
import questionary
