name: 'Remove all artifacts'

on:
  schedule:
    - cron: '0 3 * * *'  # every night at 3 am UTC

jobs:
  purge-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0
